### ISSUE TITLE
99 Chickens limit

### ISSUE THREAD

**Issue by SuspectAverage5** [kenan238/FriedChicken#1]
Issue with 99 Chickens limit. When limit is set higher than 197, the specified error is returned in the Developer Tools console:
```js
Uncaught TypeError: chicken.startsWith is not a function
    at run (app.js:434)
    at HTMLButtonElement.onclick (index.html:26)
```

**Comment by kenan238** [comment]
This is around line `434` according to the error:
```js
	if(chicken.startsWith("Error"))
```
Im gonna fix that by adding a classic try/except

**Comment by kenan238** [comment]
Check https://github.com/kenan238/FriedChicken/commit/3540fd2b007d3be189cc6805b413adf49ab1e090
